2025-02-04 21:39:51,757 INFO    MainThread:19951 [wandb_setup.py:_flush():68] Current SDK version is 0.19.5
2025-02-04 21:39:51,757 INFO    MainThread:19951 [wandb_setup.py:_flush():68] Configure stats pid to 19951
2025-02-04 21:39:51,757 INFO    MainThread:19951 [wandb_setup.py:_flush():68] Loading settings from /Users/naseunghoo/.config/wandb/settings
2025-02-04 21:39:51,757 INFO    MainThread:19951 [wandb_setup.py:_flush():68] Loading settings from /Users/naseunghoo/project/python/study-ai-mnist/week7/project/wandb/settings
2025-02-04 21:39:51,757 INFO    MainThread:19951 [wandb_setup.py:_flush():68] Loading settings from environment variables
2025-02-04 21:39:51,757 INFO    MainThread:19951 [wandb_init.py:setup_run_log_directory():637] Logging user logs to /Users/naseunghoo/project/python/study-ai-mnist/week7/project/wandb/run-20250204_213951-o2oiuwil/logs/debug.log
2025-02-04 21:39:51,757 INFO    MainThread:19951 [wandb_init.py:setup_run_log_directory():638] Logging internal logs to /Users/naseunghoo/project/python/study-ai-mnist/week7/project/wandb/run-20250204_213951-o2oiuwil/logs/debug-internal.log
2025-02-04 21:39:51,758 INFO    MainThread:19951 [wandb_init.py:init():756] calling init triggers
2025-02-04 21:39:51,758 INFO    MainThread:19951 [wandb_init.py:init():761] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-02-04 21:39:51,758 INFO    MainThread:19951 [wandb_init.py:init():789] starting backend
2025-02-04 21:39:51,990 INFO    MainThread:19951 [wandb_init.py:init():793] sending inform_init request
2025-02-04 21:39:52,014 INFO    MainThread:19951 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2025-02-04 21:39:52,014 INFO    MainThread:19951 [wandb_init.py:init():808] backend started and connected
2025-02-04 21:39:52,017 INFO    MainThread:19951 [wandb_init.py:init():901] updated telemetry
2025-02-04 21:39:52,039 INFO    MainThread:19951 [wandb_init.py:init():926] communicating run to backend with 90.0 second timeout
2025-02-04 21:39:52,384 ERROR   MainThread:19951 [wandb_init.py:init():1471] error in wandb.init()
Traceback (most recent call last):
  File "/opt/homebrew/anaconda3/envs/hanghae-subject/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1461, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/envs/hanghae-subject/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 957, in init
    raise error
wandb.errors.errors.CommError: failed to upsert bucket: returned error 403 Forbidden: {"errors":[{"message":"permission denied","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}],"data":{"upsertBucket":null}}
2025-02-04 21:39:52,391 WARNING MsgRouterThr:19951 [router.py:message_loop():75] message_loop has been closed
